export const apiCreateAlbum = "album/createAlbum"
export const apiGetDetailAlbum = "album/getDetailAlbum"
export const apiGetAllAlbumByArtist = "album/getAllAlbumByArtist"
export const apiUpdateAlbum = "album/updateAlbum"
export const apiDeleteAlbum = "album/deleteAlbum"
export const apiGetAllAlbum = "album/getAllAlbum"